FROM openjdk:8 AS BUILD_IMAGE
RUN apt update && apt install maven -y
#RUN git clone -b vp-docker https://github.com/imranvisualpath/vprofile-repo.git
RUN git clone -b vp-docker https://github.com/SwapnilDhawad/publicis_sapient_assignment.git
RUN docker pull http://34.230.35.229:8081/vproapp-31-22-10-03_1117.war
RUN cd publicis_sapient_assignment && mvn install

FROM tomcat:8-jre11

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=BUILD_IMAGE publicis_sapient_assignment/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]


http://34.230.35.229:8081/repository/weekly-release/QA/vproapp/31-22-10-03_1117/vproapp-31-22-10-03_1117.war



